#!/bin/bash
# Nagios plugin for checking a svn repo through the svn:// protocol
#
PROGNAME=`basename $0`
NAG_LEVEL="critical" # Default to critical
TMP=`mktemp -d` 
FILE=""

usage() {
	echo "Usage:"
	echo "	$PROGNAME -r <SVN_REPO> [-f FILE] [-w] [-c]"
	echo "Manditory arguments:"
	echo "	-r SVN_REPO served over the svn:// procolcol"	
	echo "     Example: -r svn://svn.kernel.org/myrepo"
	echo "Optional Arguments:"
	echo "	-f FILE that is expected to be in the SVN repository"
	echo "	-w On failure, error is warning"
	echo "	-c On failure, error is critical"
	echo ""
	echo "Examples:"
	echo "	$PROGNAME -r svn://svn.savannah.gnu.org:/srv/administration -f trunk/README -c"
	exit 1
}

cleanup(){
	rm -rf $TMP
}

nag_ok(){
	TEXT=$1
	echo "OK - $1"
	exit 0 
}

nag_err(){
	TEXT=$1
	if [ "$NAG_LEVEL" == "warning" ]; then
		echo "WARNING - $TEXT"
		exit 1
	elif [ "$NAG_LEVEL" == "critical" ]; then
		echo "CRITICAL - $TEXT"
		exit 2
	else
		echo "UNKNOWN - $TEXT"
		exit 128
			
	fi
}

trap 'cleanup' 0 1 2 3 15

while getopts "r:f:wch" opt
do
	case $opt in
		r)
			SVN_REPO=$OPTARG
			;;
		f)
			FILE=$OPTARG
			;;
		w)
			NAG_LEVEL="warning"
			;;
		c)
			NAG_LEVEL="critical"
			;;
		h)
			usage
			;;
		*)
			echo "Unknown option - $opt" 1>&2
			exit 1
			;;
	esac
done

# SVN_REPO is manditory
test -z $SVN_REPO && usage


# Try to clone the svn repot
SVN_TEXT=`svn co -q $SVN_REPO $TMP 2>&1`
SVN_TEXT=`echo $SVN_TEXT | sed "s/\n/ /g"`
if [ $? -ne 0 ]; then
	# Something went wrong, print out the svn text
	nag_err "$SVN_TEXT"
fi

# Check if we are supposed to be looking for a file
if [ -z $FILE ]; then
	# Not looking for a file
	nag_ok "SVN repo $SVN_REPO checked out to $TMP $SVN_TEXT"
fi

# If we're here, we also need a file
if [ -f $TMP/$FILE ]; then
	nag_ok "File $FILE found in SVN repo $SVN_REPO $SVN_TEXT"
else
	nag_err "File $FILE not found! - $SVN_TEXT"
fi
