#!/usr/bin/perl
# This file is part of the Savane project
# <http://gna.org/projects/savane/>
#
# : sv_update_conf.pl,v 1.22 2004/02/14 19:28:55 yeupou Exp 
# Savannah Site Configuration:
# Configuration file for a Savannah server
#
# This file has been generated by sv_update_conf
# If you modify it, run sv_update_conf --update
# to update the PHP version of this file.
# You can recreate this file using sv_update_conf --recreate
# with ease.
# Ex: sv_update_conf --conffile=/etc/savane/gnu-conf/savannah.conf --update
#     sv_update_conf --conffile=/etc/savane/gnu-conf/savannah.conf --recreate
#
# IMPORTANT SECURITY NOTE.
# Configuration files should be rwx-only for root and apache's
# user (usually "www-data" on Debian GNU/Linux).
# So the owner should be apache's user.
#      - there is a mysql password
#      - these files are executed
# While it offers the incredible advantage to avoid reinventing a boring
# config parser and to permit hackers to create very efficient config
# by using perl/php, if anybody can edit it, anybody can push savannah to 
# execute malicious code when looking for it's configuration.
# (But it's like a /etc/profile ... /etc is for admins).
#
# By default:
#      Access: (0750/-rwxr-x---)
#      Uid: (    0/root)
#      Gid: (   33/www-data)
    
use strict;

    ## SERVER(S) ##

      # Default HTTP domain
      # It must be the naked form of the domain
      # Ex: "savannah.gnu.org"
      our $sys_default_domain="savannah.gnu.org";

      # Default HTTPS domain
      # It must be the naked form of the domain
      # Ex: "savannah.gnu.org", "443"
      our $sys_https_host="$sys_default_domain";
      our $sys_https_port="443";
      
      # Brother HTTP(s) domain:
      # You can run Savannah with two different domain names. You'll be able 
      # to write a different configuration for each one.
      # The two brother/companion sites will share the same database.
      # /etc/savannah/savannah.conf.pl is far more important since the default
      # access to the database is done using this one.
      # Here you can let your savannah installation aware of the existence
      # of a brother/companion site, so while people login, it will be allowed 
      # to them to login on both site in one click.
      # If you do not have brother/companion site, comment out.
      our $sys_brother_domain="savannah.nongnu.org";

      # SQL server:
      # Ex: "localhost", "savannah", "mysqluser", "mysqlpasswd"
      our $sys_dbhost="10.1.0.101";
      #our $sys_dbparams="mysql_socket=/savannah/mysqld/mysqld.sock";
      our $sys_dbname="savane";
      our $sys_dbuser="savannahscripts";
      use File::Basename;
      open(IN, '<'.dirname(__FILE__).'/savane.pass');
      our $sys_dbpasswd = <IN>;
      chomp($sys_dbpasswd);
      close(IN);


    ## INSTALLATION PATHS ##

      # Local dir of the installation of the PHP frontend
      # IT MUST BE AN ABSOLUTE PATH NAME
      # Ex: "/usr/local/sv/src/savannah/frontend/php"
      our $sys_www_topdir="/frontend/php";
      
      # Default web directory - suffix appended to the default domain 
      # Ex: "/", "/savannah"
      our $sys_url_topdir="/";
    
      # Local dir of the site-specific content
      # Ex: "/etc/savannah/savannah-content"
      our $sys_incdir="/etc/savane/content/gnu-content";

      # [BACKEND ONLY]
      # Local dir where dumps will be stored etc
      # Ex: "/subversions/sv"
      # our $sys_miscdir="";


    ## GUI ##
      
      # Platform name, server administration project:
      # Name of the platform running and unix_group_name of the project 
      # dedicated of the server administration
      # Ex: "Savannah", "savannah", 
      our $sys_name="Savannah";
      our $sys_unix_group_name="administration";
      
      # Default locale and date formatting.
      # Ex: "fr_FR", "Y-M-d H:i"
      # our $sys_default_locale="";
      # If you want to use the default locale formating, comment out
      our $sys_datefmt="";

      # Frontend look:
      # Default theme, logo name and dimensions.
      # The engine will search for a file like 
      # savannah/www/images/$theme.theme/# our $sys_logo_name="";
      # Ex: "savannah", "floating.png", "150", "130"
      our $sys_themedefault="Savannah";
      our $sys_logo_name="floating.png";
      our $sys_logo_name_width="148";
      our $sys_logo_name_height="125";
      

    ## MAIL, MAILING-LIST ##

      # Mail domain, admin mail address, default replyto, mail address list,
      # mail aliases:
      # Ex: "gnu.org", "savannah-hackers", "nobody", "/etc/email-addresses,"
      # "/etc/aliases"
      our $sys_mail_domain="gnu.org";
      our $sys_mail_admin="savannah-reports-private";
      our $sys_mail_replyto="INVALID.NOREPLY";
      our $sys_mail_list="/etc/email-addresses";
      our $sys_mail_aliases="/etc/aliases";

    
    ## USERS ACCOUNTS ##
      
      # [BACKEND ONLY]
      # user* binaries path
      # If you do not want to use useradd/usermod/userdel that are in the
      # usual PATH but specific ones, you can type here their prefix. 
      # Otherwise, comment out.
      # If you do not know that this setting is about, comment out.
      our $sys_userx_prefix="/usr/sbin";

      # Provide login through PAM
      # (it can be AFS, Kerberos...)
      # Ex: "yes", "no"
      our $sys_use_pamauth="no";
      
      # Kerberos:
      # If you do not know what it is about, you surely don't have to
      # deal with a kerberos server, say no here.
      # IMPORTANT: this part will be removed, replaced by PAM
      # Ex: "no"
      our $sys_use_krb5="no";

      # [BACKEND ONLY]
      # User home directory
      # You can safely uncomment all these settings if you do not use
      # the savannah backend.
      # Ex: "/home"
      our $sys_homedir="/home";

      # [BACKEND ONLY]
      # User home directory subdirs
      # Ex: "2" means users will have # our $sys_homedir="";/u/us/user as home.
      our $sys_homedir_subdirs="2";

      # [BACKEND ONLY]
      # User default shell.
      # Ex: "/usr/local/bin/cvssh"
      # our $sys_shell="";


    ## CRONJOBS ##
    
      # [BACKEND ONLY]
      # Cron jobs
      # If you do not want system to be synchronized with database
      # automatically
      # on the following topics, by the backend, comment out.
      #our $sys_cron_users="yes";
      #our $sys_cron_groups="yes";
      #our $sys_cron_viewcvs_forbidden="yes";
      #our $sys_cron_mail="yes";
      #our $sys_cron_mailman="yes";
      #our $sys_cron_cleaner="yes";

    
    ## EXTRA FEATURES ##
      
      # [BACKEND ONLY]
      # viewcvs ignore list
      # If you do not use viewcvs, if you do not want the backend to
      # edit that list comment out
      our $sys_viewcvs_conffile="/savannah/etc/viewcvs/viewcvs.conf";

      # Statistics
      # If you do not have webalizer or mrtg, if you do not want comment out.
      # our $sys_webalizer_dir="";
      # our $sys_webalizer_url="";
      # our $sys_mrtg_dir="";
      # our $sys_mrtg_url="";
      # search via google added to the search module
      # our $sys_use_google=""; 
      # local admin doc: path of this path will be made available to site
      # admins
      # our $sys_localdoc_file="";

    ## DEVELOPMENT ##

      # Developers of Savannah should probably set this setting on their
      # test machine
      #our $sys_debug_on="1";

    
    ## WORKAROUNDS ##

      # DEPRECATED:
      # settings from the original SF code that does not seems usable nor 
      # usefull. They are needed in order for the PHP frontend to run for now.
      our $sys_urlroot="$sys_www_topdir/frontend/php";
      our $sys_default_dir="$sys_url_topdir";
      our $sys_nglists_domain="$sys_mail_domain";
      our $sys_replyto="$sys_mail_replyto";
      our $sys_admin_list="$sys_mail_admin";
      our $sys_shell_host="$sys_default_domain";
      our $sys_users_host="$sys_default_domain";
      our $sys_docs_host="$sys_default_domain";    
      our $sys_dns1_host="$sys_default_domain";
      our $sys_dns2_host="$sys_default_domain";
      our $sys_lists_host="$sys_default_domain";
      our $sys_lists_domain="$sys_nglists_domain";
      our $sys_email_adress="$sys_mail_admin\@$sys_mail_domain";
      our $sys_server="$sys_default_domain";
      # where are themes (original theme system). Shouldnt be modified
      our $sys_themeroot="$sys_urlroot/themes/";

# END
