#!/bin/bash

# Generated by Cherry Backup - do not modify directly, edit 'base.chb' instead


echo '* root@colonialone.fsf.org:/ -> colonialone.fsf.org/'
rsync -zavHS --delete-excluded root@colonialone.fsf.org:/ colonialone.fsf.org/ \
  \
  --exclude '*~' \
  \
  --include '/root/' \
  --include '/root/.profile' \
  --include '/root/remote_backup.sh' \
  \
  --include '/home/' \
  --include '/home/syncaliases/' \
  --include '/home/syncaliases/00_aliases/' \
  --include '/home/syncaliases/00_aliases/aliases' \
  --include '/home/syncaliases/00_aliases/README' \
  \
  --include '/etc/' \
  --include '/etc/aliases' \
  --include '/etc/cron.daily/' \
  --include '/etc/cron.daily/backup-bind' \
  --include '/etc/diffmon/' \
  --include '/etc/diffmon/diffmon.cf' \
  \
  --include '/etc/xen/' \
  --include '/etc/xen/xend-config.sxp' \
  --include '/etc/xen/auto/***' \
  --include '/etc/xen/disabled/***' \
  \
  --include '/etc/network/' \
  --include '/etc/network/interfaces' \
  --include '/etc/network/firewall.sh' \
  \
  --exclude '*'


echo '* root@savannah.gnu.org:/ -> frontend.in.sv.gnu.org/'
rsync -zavHS --delete-excluded root@savannah.gnu.org:/ frontend.in.sv.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/etc/' \
  --include '/etc/cron.daily/' \
  --include '/etc/cron.daily/sv_list_groups' \
  --include '/etc/cron.d/' \
  --include '/etc/cron.d/sv_export' \
  \
  --include '/etc/savane/' \
  --include '/etc/savane/.savane.conf.php' \
  --include '/etc/savane/savane.conf.pl' \
  \
  --exclude /etc/apache2/sites-available/default \
  --exclude /etc/apache2/sites-available/default-ssl \
  --include '/etc/apache2/' \
  --include '/etc/apache2/sites-available/***' \
  --include '/etc/apache2/conf.d/' \
  --include '/etc/apache2/conf.d/detect_bot.conf' \
  \
  --exclude '*'


echo '* root@cvs.sv.gnu.org:/ -> vcs-noshell.in.sv.gnu.org/'
rsync -zavHS --delete-excluded root@cvs.sv.gnu.org:/ vcs-noshell.in.sv.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/etc/' \
  --include '/etc/init.d/' \
  --include '/etc/init.d/cvs-permissions' \
  --include '/etc/init.d/cvs_lockdirs' \
  --include '/etc/libnss-mysql.cfg' \
  --include '/etc/libnss-mysql-root.cfg' \
  \
  --include '/etc/cron.hourly/' \
  --include '/etc/cron.hourly/bzr_commit_mail_notification' \
  --include '/etc/cron.d/' \
  --include '/etc/cron.d/rsync_external_cvs_repositories' \
  --include '/etc/cron.d/sv' \
  --include '/etc/cron.d/cvs2git' \
  --include '/etc/cron.d/truncate-gitcvs-db-log' \
  \
  --exclude /etc/apache2/sites-available/default \
  --exclude /etc/apache2/sites-available/default-ssl \
  --include '/etc/apache2/' \
  --include '/etc/apache2/sites-available/***' \
  --include '/etc/apache2/conf.d/' \
  --include '/etc/apache2/conf.d/detect_bot.conf' \
  --include '/etc/apache2/conf.d/rlimit' \
  --include '/etc/apache2/conf.d/status' \
  \
  --exclude /var/www/*/webalizer/* \
  --exclude /var/www/git/cgit/* \
  --include '/var/' \
  --include '/var/www/' \
  --include '/var/www/bzr/***' \
  --include '/var/www/cvs/***' \
  --include '/var/www/git/***' \
  --include '/var/www/hg/***' \
  --include '/var/www/svn/***' \
  --include '/var/www/off-site/' \
  --include '/var/www/off-site/README' \
  --include '/var/www/off-site/hgweb/***' \
  --include '/var/www/off-site/viewvc/' \
  --include '/var/www/off-site/viewvc/viewvc.conf' \
  --include '/var/www/off-site/viewvc/templates/' \
  --include '/var/www/off-site/viewvc/templates/include/' \
  --include '/var/www/off-site/viewvc/templates/include/header.ezt' \
  \
  --include '/etc/gitweb.conf' \
  --include '/etc/cgitrc' \
  --include '/etc/mercurial/***' \
  \
  --exclude '*'
# Mangle passwords (TODO: split them in separate file)
sed -i -e 's/^password.*/password XXXXX/' \
  vcs-noshell.in.sv.gnu.org/etc/libnss-mysql.cfg \
  vcs-noshell.in.sv.gnu.org/etc/libnss-mysql-root.cfg
# TODO: document hgweb/viewvc/cgit/etc. configurations instead of
# copying them.


echo '* root@dl.sv.gnu.org:/ -> sftp.in.sv.gnu.org/'
rsync -zavHS --delete-excluded root@dl.sv.gnu.org:/ sftp.in.sv.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/etc/' \
  --include '/etc/cron.d/' \
  --include '/etc/cron.d/download-tidyperms' \
  --include '/etc/cron.d/download-timestamp' \
  --include '/etc/cron.d/sv' \
  \
  --include '/etc/mirmon.conf' \
  \
  --exclude /etc/apache2/sites-available/default \
  --exclude /etc/apache2/sites-available/default-ssl \
  --include '/etc/apache2/' \
  --include '/etc/apache2/sites-available/***' \
  --include '/etc/apache2/conf.d/' \
  --include '/etc/apache2/conf.d/sv_dotsig' \
  \
  --exclude /var/www/*/webalizer/* \
  --exclude /var/www/arch/google* \
  --exclude /var/www/download/mirmon/* \
  --include '/var/' \
  --include '/var/www/' \
  --include '/var/www/arch/***' \
  --include '/var/www/download/***' \
  --include '/var/www/audio-video/***' \
  \
  --include '/srv/' \
  --include '/srv/download/' \
  --include '/srv/download/00_MIRRORS.*' \
  \
  --exclude '*'


echo '* root@internal.in.sv.gnu.org:/ -> internal.in.sv.gnu.org/'
rsync -zavHS --delete-excluded root@internal.in.sv.gnu.org:/ internal.in.sv.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/usr/' \
  --include '/usr/sbin/' \
  --include '/usr/sbin/rmlist' \
  --include '/usr/sbin/config_list' \
  --include '/usr/lib/' \
  --include '/usr/lib/mailman/' \
  --include '/usr/lib/mailman/bin/' \
  --include '/usr/lib/mailman/bin/change_pw' \
  \
  --include '/etc/' \
  --include '/etc/mysql/' \
  --include '/etc/mysql/my.cnf' \
  --include '/etc/mysql/my-huge.cnf' \
  --include '/etc/exim4/' \
  --include '/etc/exim4/update-exim4.conf.conf' \
  --include '/etc/munin/' \
  --include '/etc/munin/munin.conf' \
  \
  --include '/etc/cron.d/' \
  --include '/etc/cron.d/sv' \
  \
  --exclude '*'


echo '* root@builder.in.sv.gnu.org:/ -> builder.in.sv.gnu.org/'
rsync -zavHS --delete-excluded root@builder.in.sv.gnu.org:/ builder.in.sv.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/usr/' \
  --include '/usr/src/' \
  --include '/usr/src/patched/' \
  --include '/usr/src/patched/README' \
  --include '/usr/src/patched/cvs-patches/***' \
  --include '/usr/src/patched/webalizer.changelog' \
  --include '/usr/src/patched/debs/' \
  --include '/usr/src/patched/debs/README' \
  \
  --exclude '*'


echo '* root@savannah-backup.gnu.org:/ -> savannah-backup.gnu.org/'
rsync -zavHS --delete-excluded root@savannah-backup.gnu.org:/ savannah-backup.gnu.org/ \
  \
  --exclude '*~' \
  \
  --include '/root/' \
  --include '/root/restore.sh' \
  \
  --include '/etc/' \
  --include '/etc/cron.daily/' \
  --include '/etc/cron.daily/check-savannah-backup' \
  --include '/etc/cron.d/' \
  --include '/etc/cron.d/savannah-backup' \
  \
  --include '/mnt/' \
  --include '/mnt/backup/' \
  --include '/mnt/backup/backup.sh' \
  \
  --exclude '*'
