#!/bin/bash
if [ x"$1" = x"start" ]; then
    # Create CVS LockDir's in the tmpfs dir
    mkdir -m 755 $ss_/var/lock/cvs/sources /var/lock/cvs/web
    (cd /sources/; ls) | (cd /var/lock/cvs/sources && xargs mkdir -m 777)
    (cd /web/; ls) | (cd /var/lock/cvs/web && xargs mkdir -m 777)
fi
